#!/usr/bin/env python3
"""Generate the IA64 binary manifest consumed by run_iato_matrix.py."""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
from typing import Dict, List, Sequence, Tuple

ELF_MAGIC = b"\x7fELF"


def parse_root(arg: str) -> Tuple[str, Path]:
    if "=" not in arg:
        raise argparse.ArgumentTypeError(
            f"Root '{arg}' must be formatted as <category>=<path>"
        )
    category, raw_path = arg.split("=", 1)
    path = Path(raw_path).expanduser().resolve()
    return category.strip(), path


def is_elf_binary(path: Path) -> bool:
    try:
        with path.open("rb") as fh:
            return fh.read(len(ELF_MAGIC)) == ELF_MAGIC
    except OSError:
        return False


def relativize(path: Path, repo_root: Path) -> str:
    try:
        return str(path.relative_to(repo_root))
    except ValueError:
        return str(path)


def build_manifest(
    roots: Sequence[Tuple[str, Path]], repo_root: Path
) -> List[Dict[str, str]]:
    entries: List[Dict[str, str]] = []
    for category, root in roots:
        if not root.is_dir():
            raise FileNotFoundError(f"{root} is not a directory for category {category}")

        for file_path in root.rglob("*"):
            if not file_path.is_file():
                continue
            if not os.access(file_path, os.R_OK):
                continue
            if not is_elf_binary(file_path):
                continue
            entries.append(
                {
                    "path": relativize(file_path, repo_root),
                    "abs_path": str(file_path.resolve()),
                    "category": category,
                }
            )
    entries.sort(key=lambda entry: entry["path"])
    return entries


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=Path(__file__).resolve().parents[1],
        help="Repository root used for relative paths",
    )
    parser.add_argument(
        "--output",
        required=True,
        type=Path,
        help="Path to the manifest JSON to write",
    )
    parser.add_argument(
        "--cmake-output",
        type=Path,
        help="Optional path to write a CMake include with the manifest entries",
    )
    parser.add_argument(
        "--root",
        action="append",
        type=parse_root,
        required=True,
        help="Category=path pair pointing at IA64 binaries (repeatable)",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    repo_root = args.repo_root.resolve()
    roots = args.root

    manifest = build_manifest(roots, repo_root)

    output_path = args.output
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w") as fh:
        json.dump(manifest, fh, indent=2)
        fh.write("\n")

    if args.cmake_output:
        cmake_path = args.cmake_output
        cmake_path.parent.mkdir(parents=True, exist_ok=True)
        with cmake_path.open("w") as fh:
            fh.write("# Auto-generated by generate_ia64_manifest.py\n")
            fh.write("set(IATO_IA64_ENTRIES\n")
            for entry in manifest:
                fh.write(f'  "{entry["category"]}:::{entry["abs_path"]}"\n')
            fh.write(")\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

